- name: Install Nginx and Jenkins
  hosts: nodes
  become: true
  vars:
    nginx_server_name: "192.168.0.104"
    jenkins_port: 8080
  tasks:
    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Nginx on CentOS
      yum:
        name: nginx
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install Jenkins on Ubuntu
      apt:
        name: jenkins
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Jenkins on CentOS
      yum:
        name: jenkins
        state: present
      when: ansible_distribution == "CentOS"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Enable Nginx and Jenkins services
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - nginx
        - jenkins
