---
- hosts: jenkins@192.168.0.102
    vars:
    db_name: postgresql
    db_backup: postgresql_backup.sql

  tasks:
    - name: Create backup of PostgreSQL database
      become: true
      command: pg_dump {{ db_name }} > {{ db_backup }}

- hosts: node1@192.162.0.103
  tasks:
    - name: Copy backup file from source to destination
      become: true
      copy:
        src: /etc/ansible/{{ db_backup }}
        dest: /tmp/{{ db_backup }}
    - name: Restore backup to PostgreSQL database
      become: true
      command: psql {{ db_name }} < /tmp/{{ db_backup }}
